function [detail,summary] = crossvalidate_coefficient(blocks,platform)
group = findgroups(blocks.DateKey,blocks.OperationID);
groupCount = max(group);
assert(groupCount>=2,'xldturn:InsufficientGroups','Cross-validation requires >=2 operations.');
rows = cell(groupCount,1);
allObserved = [];
allPredicted = [];
for g = 1:groupCount
    train = group~=g & logical(blocks.UseForCalibration);
    test = group==g & logical(blocks.UseForCalibration);
    xTrain = blocks.SpeedAdjustedAngle_s_radpm(train);
    yTrain = blocks.ObservedExtraTime_s(train);
    cTrain = sum(xTrain.*yTrain)/sum(xTrain.^2);
    xTest = blocks.SpeedAdjustedAngle_s_radpm(test);
    yTest = blocks.ObservedExtraTime_s(test);
    predicted = cTrain*xTest;
    allObserved = [allObserved;yTest]; %#ok<AGROW>
    allPredicted = [allPredicted;predicted]; %#ok<AGROW>
    source = find(group==g,1);
    observedTotal = sum(yTest);
    predictedTotal = sum(predicted);
    rows{g} = table(platform,blocks.DateKey(source),blocks.OperationID(source), ...
        nnz(test),cTrain,sqrt(mean((yTest-predicted).^2)), ...
        mean(abs(yTest-predicted)),observedTotal,predictedTotal, ...
        predictedTotal-observedTotal, ...
        100*(predictedTotal-observedTotal)/observedTotal, ...
        'VariableNames',{'Platform','DateKey','OperationID', ...
        'HeldOutCalibrationBlocks','TrainingCoefficient_m_per_rad', ...
        'HeldOutBlockRMSE_s','HeldOutBlockMAE_s', ...
        'ObservedOperationExtraTime_s','PredictedOperationExtraTime_s', ...
        'HeldOutExtraTimeError_s','HeldOutExtraTimeRelativeError_pct'});
end
detail = vertcat(rows{:});
residual = allObserved-allPredicted;
r2zero = 1-sum(residual.^2)/sum(allObserved.^2);
relative = detail.HeldOutExtraTimeRelativeError_pct;
summary = table(platform,groupCount,numel(allObserved),r2zero, ...
    sqrt(mean(residual.^2)),mean(abs(residual)), ...
    sqrt(mean(detail.HeldOutExtraTimeError_s.^2)), ...
    mean(abs(detail.HeldOutExtraTimeError_s)),median(abs(relative)), ...
    prctile(abs(relative),95),max(abs(relative)), ...
    'VariableNames',{'Platform','HeldOutOperations','HeldOutBlocks', ...
    'CrossValidatedR2Zero','CrossValidatedBlockRMSE_s', ...
    'CrossValidatedBlockMAE_s','HeldOutExtraTimeRMSE_s', ...
    'HeldOutExtraTimeMAE_s','MedianAbsoluteExtraTimeRelativeError_pct', ...
    'P95AbsoluteExtraTimeRelativeError_pct', ...
    'MaximumAbsoluteExtraTimeRelativeError_pct'});
end
