function output = cumulative_check(blocks,model,cfg,platform)
%CUMULATIVE_CHECK Fixed-coefficient, in-sample agreement over 1--10 km.
% Per-operation percentiles are computed first; medians give equal operation weights.
base=build_one_km_units(blocks,string(platform),cfg);
assert(~isempty(base),'xldturn:NoWindows','No complete cumulative windows.');
windows=build_multiscale_windows(base,model.Coefficient_m_per_rad,string(platform),cfg);
[operationSummary,scaleSummary]=summarize_multiscale(windows,string(platform),cfg);
commonSummary=summarize_common_support(operationSummary,string(platform),cfg);
output=struct('Windows',windows,'OperationSummary',operationSummary, ...
    'ScaleSummary',scaleSummary,'CommonSupportSummary',commonSummary);
end
function base=build_one_km_units(blocks,platform,config)
group=findgroups(blocks.DateKey,blocks.OperationID);
rows=cell(height(blocks),1);cursor=0;unitID=0;
for g=1:max(group)
    index=find(group==g);d=blocks(index,:);
    origin=min(d.ArcCenter_m-d.Length_m/2);
    local=floor((d.ArcCenter_m-origin)/config.BaseWindowLength_m)+1;
    ids=unique(local).';
    for id=ids
        pick=index(local==id);length_m=sum(blocks.Length_m(pick));
        if length_m<config.MinimumWindowCoverage*config.BaseWindowLength_m
            continue
        end
        unitID=unitID+1;cursor=cursor+1;source=pick(1);
        baseline=sum(blocks.Length_m(pick)./blocks.LocalBaselineSpeed_mps(pick));
        observed=sum(blocks.Time_s(pick));
        predictor=sum(blocks.AbsoluteTurnAngle_rad(pick)./ ...
            blocks.LocalBaselineSpeed_mps(pick));
        rows{cursor}=table(platform,unitID,blocks.DateKey(source), ...
            blocks.OperationID(source),id,length_m,baseline,observed, ...
            observed-baseline,predictor,numel(pick), ...
            'VariableNames',{'Platform','UnitID','DateKey','OperationID', ...
            'WithinOperationUnit','Length_m','BaselineTime_s', ...
            'ObservedTotalTime_s','ObservedExtraTime_s', ...
            'TurnPredictor_s_per_m','Blocks'});
    end
end
base=vertcat(rows{1:cursor});
end

function windows=build_multiscale_windows(base,c,platform,config)
groups=findgroups(base.DateKey,base.OperationID);
rows=cell(height(base)*config.MaximumScale_km,1);cursor=0;windowID=0;
for g=1:max(groups)
    d=sortrows(base(groups==g,:),'WithinOperationUnit');
    ids=d.WithinOperationUnit;
    for scale=1:config.MaximumScale_km
        for startIndex=1:height(d)-scale+1
            pick=startIndex:(startIndex+scale-1);
            if any(diff(ids(pick))~=1),continue;end
            cursor=cursor+1;windowID=windowID+1;
            observedExtra=sum(d.ObservedExtraTime_s(pick));
            predictedExtra=c*sum(d.TurnPredictor_s_per_m(pick));
            observedTotal=sum(d.ObservedTotalTime_s(pick));
            predictedTotal=sum(d.BaselineTime_s(pick))+predictedExtra;
            rows{cursor}=table(platform,windowID,d.DateKey(1), ...
                d.OperationID(1),scale,ids(startIndex),sum(d.Length_m(pick)), ...
                observedExtra,predictedExtra,predictedExtra-observedExtra, ...
                observedTotal,predictedTotal,predictedTotal-observedTotal, ...
                100*(predictedTotal-observedTotal)/observedTotal, ...
                'VariableNames',{'Platform','WindowID','DateKey', ...
                'OperationID','Scale_km','StartUnit','Length_m', ...
                'ObservedExtraTime_s','PredictedExtraTime_s', ...
                'ExtraTimeError_s','ObservedTotalTime_s', ...
                'PredictedTotalTime_s','TotalTimeError_s', ...
                'TotalTimeError_pct'});
        end
    end
end
windows=vertcat(rows{1:cursor});
end

function [operationSummary,scaleSummary]=summarize_multiscale(windows,platform,config)
group=findgroups(windows.DateKey,windows.OperationID,windows.Scale_km);
rows=cell(max(group),1);
for g=1:max(group)
    d=windows(group==g,:);source=d(1,:);
    extraDenominator=sum(abs(d.ObservedExtraTime_s));
    signedExtraDenominator=sum(d.ObservedExtraTime_s);
    extraWAPE=100*sum(abs(d.ExtraTimeError_s))/extraDenominator;
    extraBias=100*sum(d.ExtraTimeError_s)/signedExtraDenominator;
    totalBias=100*sum(d.TotalTimeError_s)/sum(d.ObservedTotalTime_s);
    rows{g}=table(platform,source.DateKey,source.OperationID,source.Scale_km, ...
        height(d),extraWAPE,extraBias,median(abs(d.TotalTimeError_pct)), ...
        prctile(abs(d.TotalTimeError_pct),95),totalBias, ...
        'VariableNames',{'Platform','DateKey','OperationID','Scale_km', ...
        'Windows','ExtraTimeWAPE_pct','ExtraTimeAggregateBias_pct', ...
        'TotalTimeMdAPE_pct','TotalTimeP95APE_pct', ...
        'TotalTimeAggregateBias_pct'});
end
operationSummary=vertcat(rows{:});
summaryRows=cell(config.MaximumScale_km,1);
for scale=1:config.MaximumScale_km
    d=operationSummary(operationSummary.Scale_km==scale,:);
    raw=windows(windows.Scale_km==scale,:);
    summaryRows{scale}=table(platform,scale,height(d),height(raw), ...
        median(d.ExtraTimeWAPE_pct,'omitnan'), ...
        prctile(d.ExtraTimeWAPE_pct,25),prctile(d.ExtraTimeWAPE_pct,75), ...
        median(d.TotalTimeMdAPE_pct,'omitnan'), ...
        prctile(d.TotalTimeMdAPE_pct,25),prctile(d.TotalTimeMdAPE_pct,75), ...
        median(d.TotalTimeP95APE_pct,'omitnan'), ...
        median(d.ExtraTimeAggregateBias_pct,'omitnan'), ...
        median(d.TotalTimeAggregateBias_pct,'omitnan'), ...
        'VariableNames',{'Platform','Scale_km','Operations','Windows', ...
        'MedianOperationExtraTimeWAPE_pct','P25OperationExtraTimeWAPE_pct', ...
        'P75OperationExtraTimeWAPE_pct','MedianOperationTotalTimeMdAPE_pct', ...
        'P25OperationTotalTimeMdAPE_pct','P75OperationTotalTimeMdAPE_pct', ...
        'MedianOperationTotalTimeP95APE_pct', ...
        'MedianOperationExtraTimeAggregateBias_pct', ...
        'MedianOperationTotalTimeAggregateBias_pct'});
end
scaleSummary=vertcat(summaryRows{:});
end

function summary=summarize_common_support(operationSummary,platform,config)
maximum=operationSummary(operationSummary.Scale_km==config.MaximumScale_km,:);
eligible=string(maximum.DateKey)+"_"+string(maximum.OperationID);
keys=string(operationSummary.DateKey)+"_"+string(operationSummary.OperationID);
d=operationSummary(ismember(keys,eligible),:);
rows=cell(config.MaximumScale_km,1);
for scale=1:config.MaximumScale_km
    q=d(d.Scale_km==scale,:);
    rows{scale}=table(platform,scale,height(q),sum(q.Windows), ...
        median(q.ExtraTimeWAPE_pct,'omitnan'), ...
        median(q.TotalTimeMdAPE_pct,'omitnan'), ...
        median(q.TotalTimeP95APE_pct,'omitnan'), ...
        median(q.ExtraTimeAggregateBias_pct,'omitnan'), ...
        median(q.TotalTimeAggregateBias_pct,'omitnan'), ...
        'VariableNames',{'Platform','Scale_km','CommonOperations', ...
        'Windows','MedianOperationExtraTimeWAPE_pct', ...
        'MedianOperationTotalTimeMdAPE_pct', ...
        'MedianOperationTotalTimeP95APE_pct', ...
        'MedianOperationExtraTimeAggregateBias_pct', ...
        'MedianOperationTotalTimeAggregateBias_pct'});
end
summary=vertcat(rows{:});
end
