function [panelLabel,titleLabel]=style_draft_axes(ax,cfg,letter,titleText)
set(ax,'FontName',cfg.FontName,'FontSize',cfg.TickFont,'TickDir','in', ...
 'TickLength',[.012 .012],'LineWidth',cfg.LineWidth,'XColor','k','YColor','k', ...
 'XMinorTick','off','YMinorTick','off','Layer','top');
box(ax,'on');grid(ax,'off');
drawnow;boxPosition=tightPosition(ax);gap=cfg.PanelLabelGap_cm/boxPosition(4);
panelLabel=text(ax,-.16,1+gap,sprintf('(%c)',letter),'Units','normalized', ...
 'FontName',cfg.FontName,'FontSize',cfg.PanelFont,'FontWeight','normal', ...
 'VerticalAlignment','bottom','Clipping','off','Interpreter','none');
titleLabel=text(ax,.01,1+gap,titleText,'Units','normalized','FontSize',cfg.PanelFont, ...
 'VerticalAlignment','bottom','Clipping','off','Interpreter','tex');
end
