function checks = check_case(info,segments,time,xyz,aux,intersections,metrics,ctx,cfg)
%CHECK_CASE Acceptance of complete physical route, real DEM sampling, auxiliaries and mask.
names=["route closure";"exact mapped control vertices";"all route roles measured"; ...
 "segment lengths close";"finite sampled bed elevations";"auxiliary line count"; ...
 "finite auxiliary elevations";"all evaluation cells retained";"native plus fill close";"nonnegative RMSE"];
errors=[norm(info.trajectory(1,:)-info.trajectory(end,:));double(~info.turnPointsIncluded); ...
 nnz(~segments.IsMeasured);abs(sum(segments.Length_m)-time.PathLength_m(1)); ...
 nnz(~isfinite(xyz(:,3)));abs(numel(unique(aux.ID))-cfg.AuxiliaryLineCount); ...
 nnz(~isfinite(aux.Z));abs(metrics.EvaluationCells-numel(ctx.EvaluationIndices)); ...
 abs(metrics.NativeNNCells+metrics.ExteriorFillCells-metrics.EvaluationCells);double(metrics.RMSE_m<0)];
tolerances=[1e-7;0;0;1e-6;0;0;0;0;0;0];
checks=table(names,errors,tolerances,isfinite(errors)&errors<=tolerances, ...
 'VariableNames',{'Check','AbsoluteDifference','Tolerance','Pass'});
for id=reshape(unique(aux.ID),1,[])
    a=aux(aux.ID==id,:);i=intersections(intersections.ID==id,:);
    e=max(abs([min(i.S);max(i.S)]-[a.S(1);a.S(end)]));
    checks=[checks;table("auxiliary "+id+" measured endpoint anchors",e,cfg.AnchorTolerance_m,e<=cfg.AnchorTolerance_m, ...
       'VariableNames',checks.Properties.VariableNames)]; %#ok<AGROW>
end
if info.scheme=='D'
    e=mod(info.effectiveIntervalCount,2);checks=[checks;table("PCZ effective intervals even",e,0,e==0, ...
       'VariableNames',checks.Properties.VariableNames)];
end
end
